spring:
  application:
    name: "configserver"
  profiles:
    # has to be used if config files were stored in class path
    #active: native
    active: git
  cloud:
    config:
      server:
       # native:
          # search-locations: "classpath:/config" # used when the config files are stored in classpath
          # search-locations: "file:///Users//eazybytes//Documents//config"  -- > should be used when configs are stored in file system.
        git:
          uri: "https://github.com/imMutharasuchandrasekar/finnovate-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071