spring:
  application:
    name: "configserver"
  profiles:
    # has to be used if config files were stored in class path
    active: native
    # active: git
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"




server:
  port: 8071