# All the mcs can be built, started/stoped and configured using this single file.
# Although it is generic & controls all mcs, adding this file in accounts just to push it.
# To start all existing containers - docker compose start
# To stop all existing containers - docker compose stop
# To create & start all containers - docker compose up -d
# To stop & remove all existing containers - docker compose stop
services:
  configserver:
    image: "mutharasuc/configserver"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "mutharasuc/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "mutharasuc/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "mutharasuc/cards"
    container_name: cards-ms
    ports:
      - "9001:9001"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

# Creates a network by the mcs can communicate with each other.
networks:
  finnovate:
    driver: "bridge"
